name: Update Weather Data FIXED
permissions:
  contents: write

on:
  schedule:
    - cron: "0 4 * * *"   # 7 AM Athens (UTC+3, summer time)
    - cron: "0 14 * * *"  # 5 PM Athens (UTC+3, summer time)
  workflow_dispatch:        # keep manual trigger option too

jobs:
  update-weather:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        batch: [0]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run weather updater
        run: python weather_update.py --once --batch-size 10 --batch-number 0

      - name: Commit and push
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add weather_cache.json
          git commit -m "Update weather cache" || echo "No changes to commit"
          git pull --rebase
          git push
